name: Run mypy and ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3

      - name: Run dependency libraries
        run: |
          apt update
          apt upgrade
          apt install -y ffmpeg
      
      - name: Run dependency libraries
        run: |
          pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 torchtext==0.16.0
          pip install decord mypy ruff
      
      - name: Run mypy
        run: mypy videoLLM_suite

      - name: Run ruff
        run: ruff check videoLLM_suite
